### ISSUE TITLE
Random mode

### ISSUE THREAD

**Issue by kpot87** [djarumlights/BitCrack#2]
Hi! Can you explaine how random mode works? It’s generating 3 start points and start check parallel this start 3 points or it’s checks first point until it’s calculated 1billion variants the second point and etc. tnx

**Comment by RastaDollo** [comment]
More starting points are generated, depends on settings and video card, shows random three

**Comment by kpot87** [comment]
![2E917D26-6C1A-438D-842B-47C8C8681D90](https://user-images.githubusercontent.com/63202750/84507902-31f91480-acca-11ea-8bce-b45613b3c831.jpeg)
@RastaDollo  For example I have generated 53m points and I have three start points, what’s next ? Thank you
