### ISSUE TITLE
E0322 use of object of abstract type of class "CLKeySearchDevice" is not allowed: clKeyFinder

### ISSUE THREAD

**Issue by Noname400** [djarumlights/BitCrack#4]
I am grateful to you for your work. You have done a great job. But I am having difficulty compiling the OPENCL.

I compiled CUDA without problems.
I will be very grateful if you can help me find the reason.

ERROR:
E0322 use of object of abstract type of class "CLKeySearchDevice" is not allowed: clKeyFinder
C2259 "CLKeySearchDevice": unable to instantiate abstract class clKeyFinder

**Comment by huk87** [comment]
Have you figured it out? Please share with me the exe file clKeyFinder.exe if you are ready.

**Comment by Noname400** [comment]
clKeyFinder.exe not random mode

**Comment by Noname400** [comment]
I use https://github.com/kanhavishva/BitCrack2
