### ISSUE TITLE
period of time

### ISSUE THREAD

**Issue by Noname400** [djarumlights/BitCrack#7]
hello, please add a change of points after a period of time.

For example: at startup, 16,000,000 random points are created and every 30 minutes they are randomly generated again.

**Comment by RastaDollo** [comment]
Need 2 bat files.
Creat folder c:\bitcrack and put inside cubitcrack.exe and btc.txt, then creat RUN.bat and RESTART.bat.

In run.bat creat:

cd C:\Bitcrack
:loop
cuBitCrack.exe -c -u -r -b 384 -t 256 -p 136 -i btc.txt -o key.txt —keyspace 0000100000000000000000000000001000000000000000000000000000000000:FFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140
goto :loop

In restart.bat creat:

C:\Bitcrack\run.bat
:loop
timeout /t 1800 /nobreak
taskkill /f /im cubitcrack.exe
Goto :loop

Now double click on restart.bat

*-b -t -p your videocard parametrs
*If change 1800 to 600 restart will be 10min
*sorry my bad english
Peace

**Comment by Noname400** [comment]
Я это и так сделал. Но немного по другому.
Но файл с адресами весит 3.2 гб. 
Создание блюм фильтра занимает очень много времени.
